# ENGLISH
[other]
main = "Main"
list = "List"

[projects]
title = "Main"
header = "This are all of my current projects!"

# Projects under 'Games'
[games]
title = "Games"

[games.pollimath]
name = "PolliMath"
desc = "A game about a chick and... Algebra?"

[games.circulatory_system]
name = "Circulatory System"
desc = "Study about the functions of the circulatory system!"

[games.gegagedigedagedago]
name = "Gegagedigedagedago VS"
desc = "Fight against the evil egg in an epic wild west showdown!!!1!!1"

[games.space_arithmetic]
name = "Space Arithmetic"
desc = "A game about basic arithmetic."

[games.habanero_cheese]
name = "Habanero Cheese"
desc = "An habanero cheese that burns trash..."

[games.lines]
name = "Lines"
desc = "An educative game about line⁠-line and circle⁠-line intersections"

# Projects under 'Apps'
[app]
title = "Apps"

[app.musicapp]
name = "NachoMusic"
desc = "An Android Music app that can download and play music offline!"

# Projects under 'Websites'
[web]
title = "Websites"

[web.oxidation]
name = "New: Practice Oxidation"
desc = "Practice element oxidation numbers and more!"

[web.celebration_envelopes]
name = "Celebration Envelopes"
desc = "Make celebration envelopes for your loved ones!"

[web.midinotes]
name = "MidiNotes"
desc = "Connect your keyboard and practice any MIDI song!"

[web.secret_santa]
name = "Secret Santa"
desc = "Anoyed that your secret santa breaks its flow? Well now no more!"

[web.tileset_assembler]
name = "Tileset Assembler"
desc = "Make your Pizza Tower tilesets go smoothly! Also hide all collisions!"

[web.coolrhythms]
name = "CoolRhythms"
desc = "The website for the youtuber CoolRhythms"

[web.flavortown_devlog_exporter]
name = "Flavortown Devlog Exporter"
desc = "A browser extension for Hack Club's Flavortown, it allows users to export project's devlogs and details."

[web.pyramid_scheme_translator]
name = "Pyramid Scheme Translator"
desc = "A tool for Hack Club's referral program, \"Pyramid Scheme\"; it allows users to translate the generated posters into other languages."

# Projects under 'Mods'
[mods]
title = "Mods"

[mods.bocs]
name = "Bunch Of Complex Stuff (BOCS)"
desc = "GD like triggers in Pizza Tower"

# Achievements
[achievements]
title = "Achievements"
header = "This are my achievements"

[achievements.courses]
title = "Courses"
cs50x = "CS50x by Harvard"

[achievements.olympiads]
title = "Olympiads"
oci = "Costa Rican Olympiad in Informatics (OCI)"
ioi = "International Olympiad in Informatics (IOI)"
oicc = "Caribean and Central American Olympiad in Informatics (OICC)"
oii = "Ibero-American Olympiad in Informatics (OII)"
