# ESPANOL
[other]
main = "Principal"
list = "Lista"

[projects]
title = "Principal"
header = "¡Estos son todos mis proyectos actuales!"

# Projects under 'Games'
[games]
title = "Juegos"

[games.pollimath]
name = "PolliMath"
desc = "Un juego de un pollito y ¿Algebra?"

[games.circulatory_system]
name = "Sistema Circulatorio"
desc = "¡Estudia sobre las funciones del sistema circulatorio!"

[games.gegagedigedagedago]
name = "Gegagedigedagedago VS"
desc = "Lucha contra el huevo malvado!!!1!!1"

[games.space_arithmetic]
name = "Aritmética Espacial"
desc = "Juego de aritmética básica."

[games.habanero_cheese]
name = "Habanero Cheese"
desc = "Un queso de habanero que quema basura..."

[games.lines]
name = "Lineas"
desc = "Un juego educativo sobre intersecciones linea⁠-linea y circumferencias⁠-linea."

# Projects under 'Apps'
[app]
title = "Aplicaciones"

[app.musicapp]
name = "NachoMusic"
desc = "¡Una app para Android de Musica con descargas y reproduccion offline!"

# Projects under 'Websites'
[web]
title = "Páginas Web"

[web.oxidation]
name = "Nuevo: Practicar Oxidos"
desc = "¡Practica numeros de oxidacion de elementos y mas!"

[web.celebration_envelopes]
name = "Celebration Envelopes"
desc = "¡Crea 'cartas' de celebración para tus conocidos!"

[web.midinotes]
name = "MidiNotes"
desc = "¡Conecta tu teclado y practica toda canción en Midi!"

[web.secret_santa]
name = "Amigo Secreto"
desc = "¿Estresado porque los Amigos Secreto se cortan? ¡Pues este no!"

[web.tileset_assembler]
name = "Tileset Assembler"
desc = "Haz que los tilesets de Pizza Tower no den Lag! Tambien esconde las colisiones!"

[web.coolrhythms]
name = "CoolRhythms"
desc = "¡El sitio web del Youtuber de música CoolRhythms!"

[web.flavortown_devlog_exporter]
name = "Flavortown Devlog Exporter"
desc = "Una extensión de buscadores para el programa de Hack Club, Flavortown; permite a los usuarios exportar la bitacora y detalles de los proyectos."

[web.pyramid_scheme_translator]
name = "Pyramid Scheme Translator"
desc = "Una herramienta para el programa de referencias de Hack Club, \"Pyramid Scheme\"; permite a los usuarios traducir los posters a otros idiomas."

# Projects under 'Mods'
[mods]
title = "Mods"

[mods.bocs]
name = "Bunch Of Complex Stuff (BOCS)"
desc = "Triggers de GD en Pizza Tower."

# Achievements
[achievements]
title = "Logros"
header = "Estos son mis logros"

[achievements.courses]
title = "Cursos"
cs50x = "CS50x de Harvard"

[achievements.olympiads]
title = "Olimpiadas"
oci = "Olimpiada Costarricense de Informática (OCI)"
ioi = "Olimpiada Internacional de Informática (IOI)"
oicc = "Olimpiada Centroamericana y Caribeña de Informática (OICC)"
oii = "Olimpiada Iberoamericana de Informática (OII)"
